/* The next/font wrappers, from the weight ladder rather than by hand.
 *
 * These list every static cut with the weight it answers to, and the list was
 * maintained by hand against filenames that had been renamed on the way into
 * the package — so `Zen-Black.woff2` was declared at 800 and the file renamed
 * from ExtraBold at 900, and a page asking for 900 got the 800 face. A ladder
 * cannot be off by one against itself.
 *
 * Run: node scripts/next.mjs   (writes dist/{font,sans-non-variable,mono-non-variable}.js)
 */
import { writeFileSync, existsSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist')

/* The CSS weight ladder. The name is the file's, and the number is what a page
   asks for — one row, so they cannot disagree. */
const LADDER = [
  [100, 'Thin'], [200, 'ExtraLight'], [300, 'Light'], [400, 'Regular'], [500, 'Medium'],
  [600, 'SemiBold'], [700, 'Bold'], [800, 'ExtraBold'], [900, 'Black'],
]

const FALLBACK = {
  sans: ['ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto',
    'Helvetica Neue', 'Arial', 'sans-serif'],
  mono: ['ui-monospace', 'SFMono-Regular', 'Roboto Mono', 'Menlo', 'Monaco',
    'Liberation Mono', 'DejaVu Sans Mono', 'Courier New', 'monospace'],
}

const FAMILY = {
  sans: { dir: 'zen-sans', stem: 'Zen', export: 'ZenSans', variable: '--font-zen-sans' },
  mono: { dir: 'zen-mono', stem: 'ZenMono', export: 'ZenMono', variable: '--font-zen-mono' },
}

/* Italic is a separate file, so a non-variable page that leaves it out gets a
   slanted copy of the roman. Every cut that exists is listed. */
const faces = ({ dir, stem }) =>
  LADDER.flatMap(([weight, name]) =>
    [['normal', name], ['italic', name === 'Regular' ? 'Italic' : `${name}Italic`]]
      .map(([style, tail]) => ({ file: `${stem}-${tail}.woff2`, weight, style }))
      .filter((f) => existsSync(join(DIST, 'fonts', dir, f.file))))

const src = (family) => faces(FAMILY[family]).map((f) =>
  `    {\n      path: "./fonts/${FAMILY[family].dir}/${f.file}",\n` +
  `      weight: "${f.weight}",\n      style: "${f.style}",\n    },`).join('\n')

const block = (family, extra = '') =>
  `export const ${FAMILY[family].export} = localFont({\n  src: [\n${src(family)}\n  ],\n` +
  `  variable: "${FAMILY[family].variable}",\n${extra}` +
  `  fallback: [\n${FALLBACK[family].map((f) => `    "${f}",`).join('\n')}\n  ],\n});\n`

/* The ladder must cover the build, not just agree with itself. A cut that
   exists and is not named here is a weight a page cannot ask for, and the
   generator has no way to notice — so it looks. */
for (const [family, { dir }] of Object.entries(FAMILY)) {
  const listed = new Set(faces(FAMILY[family]).map((f) => f.file))
  const missing = readdirSync(join(DIST, 'fonts', dir))
    .filter((f) => f.endsWith('.woff2') && !f.includes('Variable') && !listed.has(f))
  if (missing.length) throw new Error(`${dir}: the ladder does not name ${missing.join(', ')}`)
}

const head = '// Generated by scripts/next.mjs. Do not edit.\nimport localFont from "next/font/local";\n\n'
const mono = '  adjustFontFallback: false,\n'

writeFileSync(join(DIST, 'font.js'), head + block('sans') + '\n' + block('mono', mono))
writeFileSync(join(DIST, 'sans-non-variable.js'), head + block('sans'))
writeFileSync(join(DIST, 'mono-non-variable.js'), head + block('mono', mono))
console.log('wrote dist/{font,sans-non-variable,mono-non-variable}.js —',
  faces(FAMILY.sans).length, 'sans cuts,', faces(FAMILY.mono).length, 'mono cuts')
