/* The Zen presets, defined once and emitted twice.
 *
 * Each is a point in Zen's own parameter space that a brand has settled on, so a
 * surface names the voice ("wide") rather than restating three numbers that then
 * drift between the stylesheet and the component.
 *
 * The two that replace a licensed face were FITTED, not chosen: render the target,
 * render Zen at a candidate (wght, scaleX, track), normalise both to one cap height
 * and score the pixel residual, then search. `residual` records how well the winner
 * did, because a preset that is a strong resemblance and a preset that is a match
 * should not look the same in the source.
 *
 * Run: node scripts/presets.mjs   (writes dist/presets.css and dist/presets.js)
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist')

export const PRESETS = {
  air: {
    wght: 220, scaleX: 1, track: -0.03,
    note: 'Thin display. Hanzo’s headline voice.',
  },
  book: {
    wght: 497, scaleX: 1, track: 0,
    note: 'Text. Fitted to a text face.',
    fits: 'a text face', residual: 0.297,
  },
  medium: {
    wght: 606, scaleX: 1, track: 0,
    note: 'UI emphasis. Fitted to a text face — within 1.6% on every outline ratio.',
    fits: 'a text face', residual: 0.254,
  },
  wide: {
    wght: 845, scaleX: 1.40, track: -0.04,
    note: 'Monumental caps. Fitted to the LUX wordmark.',
    fits: 'the LUX wordmark', residual: 0.176,
  },
  round: {
    wght: 900, scaleX: 1, track: -0.018,
    note: 'Heavy and friendly at large sizes. Zoo’s display voice.',
  },
}

/* A surface REPLACING the previous face multiplies its font-size by this; a surface simply
   using Zen does not. It is deliberately not baked into `book`/`medium` — the
   preset is a voice, this is a migration correction, and braiding them would
   apply it to type that never saw the previous face.

   DIVIDE BY THE EM, NOT THE CAP, and that is the whole subtlety. `font-size` and
   `size-adjust` both scale the em, so matching x-heights means matching
   x-per-em:

     the previous face  xh 494 / upem 1000 = 0.4940
     Zen    xh 530 / upem 1000 = 0.5300
     factor = 0.4940 / 0.5300  = 0.9321

   This shipped as 0.962 first, derived from the same two faces' x-per-CAP
   (0.7180 / 0.7465). Those cap ratios are correct and the arithmetic on them is
   correct — it just answers a question nobody asked, because no CSS property
   scales a glyph by its cap height. The result was type still 3.2% larger than
   the the previous face it replaced: better than the 6.8% of no correction at all, and close
   enough to read as done while being wrong. Any surface that applied 0.962
   should move to this value. */
export const XHEIGHT_FACTOR = 0.9321

const decl = (p) => {
  const out = [`font-variation-settings:'wght' ${p.wght}`]
  if (p.track) out.push(`letter-spacing:${p.track}em`)
  if (p.scaleX !== 1) out.push(
    `transform:scaleX(${p.scaleX})`, 'transform-origin:left center', 'display:inline-block')
  return out.join(';')
}

const css = `/* Zen presets — generated by scripts/presets.mjs. Do not edit.
 *
 *   import '@hanzo/font/css'        the faces
 *   import '@hanzo/font/presets'    these
 *
 * A preset sets weight, and where the fit required it, tracking and a horizontal
 * scale. Anything that scales is inline-block with a left origin, and its LAYOUT
 * box stays the untransformed width — a transform does not reflow, so give
 * .zen-wide room or clip its container.
 */
${Object.entries(PRESETS).map(([k, p]) =>
  `\n/* ${p.note}${p.fits ? ` (${(p.residual * 100).toFixed(1)}% residual)` : ''} */\n` +
  `.zen-${k}{${decl(p)}}`).join('\n')}

:root{
${Object.entries(PRESETS).map(([k, p]) =>
  `  --zen-${k}-wght:${p.wght};` +
  (p.track ? `--zen-${k}-track:${p.track}em;` : '') +
  (p.scaleX !== 1 ? `--zen-${k}-scale-x:${p.scaleX};` : '')).join('\n')}
  --zen-xheight-factor:${XHEIGHT_FACTOR};
}
`

const js = `// Generated by scripts/presets.mjs. Do not edit.
export const PRESETS = ${JSON.stringify(PRESETS, null, 2)}
export const XHEIGHT_FACTOR = ${XHEIGHT_FACTOR}

/** Style object for a preset — for a surface that styles in code, not CSS. */
export function preset(name) {
  const p = PRESETS[name]
  if (!p) throw new Error(\`no Zen preset "\${name}" — have \${Object.keys(PRESETS).join(', ')}\`)
  return {
    fontFamily: 'Zen',
    fontVariationSettings: \`'wght' \${p.wght}\`,
    ...(p.track ? { letterSpacing: \`\${p.track}em\` } : {}),
    ...(p.scaleX !== 1
      ? { transform: \`scaleX(\${p.scaleX})\`, transformOrigin: 'left center', display: 'inline-block' }
      : {}),
  }
}
`

const dts = `export interface ZenPreset {
  wght: number
  scaleX: number
  track: number
  note: string
  fits?: string
  residual?: number
}
export declare const PRESETS: Record<'air' | 'book' | 'medium' | 'wide' | 'round', ZenPreset>
export declare const XHEIGHT_FACTOR: number
export declare function preset(name: keyof typeof PRESETS): Record<string, string | number>
`

writeFileSync(join(DIST, 'presets.css'), css)
writeFileSync(join(DIST, 'presets.js'), js)
writeFileSync(join(DIST, 'presets.d.ts'), dts)
console.log('wrote dist/presets.{css,js,d.ts} —', Object.keys(PRESETS).join(' '))
