/* The Zen presets, defined once and emitted twice.
 *
 * Each is a point in Zen's own parameter space that a brand has settled on, so a
 * surface names the voice ("wide") rather than restating three numbers that then
 * drift between the stylesheet and the component.
 *
 * The three that match something were FITTED, not chosen, and TWO DIFFERENT METRICS
 * are involved — which is why they are two different fields rather than one number
 * that means whichever thing you assumed:
 *
 *   residual   coverage. Render target and candidate at one cap height, take the
 *              pixel difference as a fraction of target ink. Whole-mark, so it is
 *              dominated by width and position.
 *   within     the worst single FEATURE — stem width, bar thickness — as a ratio to
 *              the target's. Coverage cannot see a thin bar behind a correct width,
 *              and on the LUX wordmark it scored 17% while the bars ran 21-29% thin.
 *
 * A 3.2% `within` and a 25.4% `residual` are not comparable and must not be read
 * as one being eight times better than the other.
 *
 * Run: node scripts/presets.mjs   (writes dist/presets.css and dist/presets.js)
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist')

export const PRESETS = {
  air: {
    wght: 220, scaleX: 1, track: -0.03,
    note: 'Thin display. Hanzo’s headline voice.',
  },
  book: {
    wght: 497, scaleX: 1, track: 0,
    note: 'Text. Fitted to Basel Grotesk Book.',
    fits: 'Basel Grotesk Book', residual: 0.297,
  },
  medium: {
    wght: 606, scaleX: 1, track: 0,
    note: 'UI emphasis. Fitted to Basel Grotesk Medium — within 1.6% on every outline ratio.',
    fits: 'Basel Grotesk Medium', residual: 0.254,
  },
  wide: {
    // The wordmark's own geometry, so caps set here sit with it rather than
    // near it. It was 1.56 while the mark solved to 1.4861 — 5% apart, which is
    // visible the moment the two meet.
    //
    // No diagonal weight, and that is measured rather than assumed. The mark
    // gives its X its own heavier instance because one letter can be aimed at
    // one target; doing the same across an alphabet makes it WORSE — evenness
    // 1.90 -> 2.17. A heavier whole glyph thickens a letter's UPRIGHT too, so K
    // goes +21%, and each letter's angle responds differently, so A, V and W
    // overshoot by 7-9% while M and Y do not move at all.
    //
    // What remains is the face's own drawing: the uprights hold 0.293-0.295
    // across BDEFHIJKLNPRTU, diagonals run about 13% under it, and the round
    // forms 3-17% under at their thinnest point, which is how a round letter is
    // drawn. Evenness 1.90, widest over narrowest.
    wght: 650, scaleX: 1.4861, track: -0.095,
    note: 'Monumental caps. Set to sit with the LUX wordmark.',
    fits: 'the LUX wordmark', within: 0.026,
  },
  round: {
    wght: 900, scaleX: 1, track: -0.018,
    note: 'Heavy and friendly at large sizes. Zoo’s display voice.',
  },
}

/* A surface REPLACING Basel multiplies its font-size by this; a surface simply
   using Zen does not. It is deliberately not baked into `book`/`medium` — the
   preset is a voice, this is a migration correction, and braiding them would
   apply it to type that never saw Basel.

   DIVIDE BY THE EM, NOT THE CAP, and that is the whole subtlety. `font-size` and
   `size-adjust` both scale the em, so matching x-heights means matching
   x-per-em:

     Basel  xh 494 / upem 1000 = 0.4940
     Zen    xh 530 / upem 1000 = 0.5300
     factor = 0.4940 / 0.5300  = 0.9321

   This shipped as 0.962 first, derived from the same two faces' x-per-CAP
   (0.7180 / 0.7465). Those cap ratios are correct and the arithmetic on them is
   correct — it just answers a question nobody asked, because no CSS property
   scales a glyph by its cap height. The result was type still 3.2% larger than
   the Basel it replaced: better than the 6.8% of no correction at all, and close
   enough to read as done while being wrong. Any surface that applied 0.962
   should move to this value. */
export const BASEL_XHEIGHT_FACTOR = 0.9321

const decl = (p) => {
  const out = [`font-variation-settings:'wght' ${p.wght}`]
  if (p.track) out.push(`letter-spacing:${p.track}em`)
  if (p.scaleX !== 1) out.push(
    `transform:scaleX(${p.scaleX})`, 'transform-origin:left center', 'display:inline-block')
  return out.join(';')
}

const css = `/* Zen presets — generated by scripts/presets.mjs. Do not edit.
 *
 *   import '@hanzo/font/css'        the faces
 *   import '@hanzo/font/presets'    these
 *
 * A preset sets weight, and where the fit required it, tracking and a horizontal
 * scale. Anything that scales is inline-block with a left origin, and its LAYOUT
 * box stays the untransformed width — a transform does not reflow, so give
 * .zen-wide room or clip its container.
 */
${Object.entries(PRESETS).map(([k, p]) =>
  `\n/* ${p.note}${p.residual ? ` (${(p.residual * 100).toFixed(1)}% coverage residual)` : ''}` +
  `${p.within ? ` (within ${(p.within * 100).toFixed(1)}% on every feature)` : ''} */\n` +
  `.zen-${k}{${decl(p)}}`).join('\n')}

:root{
${Object.entries(PRESETS).map(([k, p]) =>
  `  --zen-${k}-wght:${p.wght};` +
  (p.track ? `--zen-${k}-track:${p.track}em;` : '') +
  (p.scaleX !== 1 ? `--zen-${k}-scale-x:${p.scaleX};` : '')).join('\n')}
  --zen-basel-xheight-factor:${BASEL_XHEIGHT_FACTOR};
}
`

const js = `// Generated by scripts/presets.mjs. Do not edit.
export const PRESETS = ${JSON.stringify(PRESETS, null, 2)}
export const BASEL_XHEIGHT_FACTOR = ${BASEL_XHEIGHT_FACTOR}

/** Style object for a preset — for a surface that styles in code, not CSS. */
export function preset(name) {
  const p = PRESETS[name]
  if (!p) throw new Error(\`no Zen preset "\${name}" — have \${Object.keys(PRESETS).join(', ')}\`)
  return {
    fontFamily: 'Zen',
    fontVariationSettings: \`'wght' \${p.wght}\`,
    ...(p.track ? { letterSpacing: \`\${p.track}em\` } : {}),
    ...(p.scaleX !== 1
      ? { transform: \`scaleX(\${p.scaleX})\`, transformOrigin: 'left center', display: 'inline-block' }
      : {}),
  }
}
`

const dts = `export interface ZenPreset {
  wght: number
  scaleX: number
  track: number
  note: string
  fits?: string
  /** Coverage: whole-mark pixel difference as a fraction of target ink. */
  residual?: number
  /** The worst single feature — stem, bar — as a ratio to the target's. */
  within?: number
}
export declare const PRESETS: Record<'air' | 'book' | 'medium' | 'wide' | 'round', ZenPreset>
export declare const BASEL_XHEIGHT_FACTOR: number
export declare function preset(name: keyof typeof PRESETS): Record<string, string | number>
`

/* The Rust crate needs these numbers too — the CLI prints them and the wasm
   build serves them — and a second hand-maintained copy is a second thing to
   forget. It is generated here rather than read at run time because the crate
   compiles to wasm with no filesystem. */
/* A Rust float literal: 1 is not f32 there, 1.0 is. */
const f = (n) => (Number.isInteger(n) ? `${n}.0` : String(n))

const rs = `// Generated by packages/zen/scripts/presets.mjs. Do not edit.
use crate::Preset;

pub const PRESETS: [Preset; ${Object.keys(PRESETS).length}] = [
${Object.entries(PRESETS).map(([k, p]) =>
  // Emit the number, not a rounding of it. `toFixed(2)` shipped the crate
  // scale_x 1.49 while the CSS got 1.4861 — the same fact at two precisions,
  // which is the whole failure this file exists to prevent. `f` keeps a whole
  // number a float, since Rust will not read `1` as f32.
  `    Preset { name: ${JSON.stringify(k)}, wght: ${f(p.wght)}, ` +
  `scale_x: ${f(p.scaleX)}, track: ${f(p.track)}, ` +
  `residual: ${p.residual ? `Some(${p.residual})` : 'None'}, ` +
  `within: ${p.within ? `Some(${p.within})` : 'None'} },`).join('\n')}
];
`
writeFileSync(join(DIST, '..', '..', '..', 'crates', 'zen', 'src', 'presets.rs'), rs)

writeFileSync(join(DIST, 'presets.css'), css)
writeFileSync(join(DIST, 'presets.js'), js)
writeFileSync(join(DIST, 'presets.d.ts'), dts)
console.log('wrote dist/presets.{css,js,d.ts} —', Object.keys(PRESETS).join(' '))
