// Generated by packages/zen/scripts/presets.mjs. Do not edit.
use crate::Preset;

pub const PRESETS: [Preset; 5] = [
    Preset { name: "air", wght: 220.0, scale_x: 1.0, track: -0.03 },
    Preset { name: "book", wght: 497.0, scale_x: 1.0, track: 0.0 },
    Preset { name: "medium", wght: 606.0, scale_x: 1.0, track: 0.0 },
    Preset { name: "wide", wght: 650.0, scale_x: 1.4861, track: -0.095 },
    Preset { name: "round", wght: 900.0, scale_x: 1.0, track: -0.018 },
];
