// Generated by scripts/next.mjs. Do not edit.
import { NextFontWithVariable } from "next/dist/compiled/@next/font";

export declare const Zen: NextFontWithVariable;
export declare const ZenMono: NextFontWithVariable;
export declare const ZenPixelCircle: NextFontWithVariable;
export declare const ZenPixelGrid: NextFontWithVariable;
export declare const ZenPixelLine: NextFontWithVariable;
export declare const ZenPixelSquare: NextFontWithVariable;
export declare const ZenPixelTriangle: NextFontWithVariable;
