// Generated by scripts/next.mjs. Do not edit.
import { NextFontWithVariable } from "next/dist/compiled/@next/font";

/**
 * The text face. Variable over wght 100-900, so any weight the design reaches for already exists.
 *
 * Declares `font-family: 'Zen'` and sets `--font-zen-sans`.
 *
 * Attach `.variable` to a wrapper to publish the custom property, or
 * `.className` to set the family directly on an element.
 *
 * @see {@link https://font.hanzo.ai Specimen and downloads}
 */
export declare const Zen: NextFontWithVariable;

/**
 * The companion monospace, for code, data and anything that has to line up. Variable over wght 100-900.
 *
 * Declares `font-family: 'Zen Mono'` and sets `--font-zen-mono`.
 *
 * Attach `.variable` to a wrapper to publish the custom property, or
 * `.className` to set the family directly on an element.
 *
 * @see {@link https://font.hanzo.ai Specimen and downloads}
 */
export declare const ZenMono: NextFontWithVariable;

/**
 * A display face drawn in circle pixels. One weight — the five Pixel cuts are five drawings of one alphabet, not five weights of one drawing.
 *
 * Declares `font-family: 'Zen Pixel Circle'` and sets `--font-zen-pixel-circle`.
 *
 * Attach `.variable` to a wrapper to publish the custom property, or
 * `.className` to set the family directly on an element.
 *
 * @see {@link https://font.hanzo.ai Specimen and downloads}
 */
export declare const ZenPixelCircle: NextFontWithVariable;

/**
 * A display face drawn in grid pixels. One weight — the five Pixel cuts are five drawings of one alphabet, not five weights of one drawing.
 *
 * Declares `font-family: 'Zen Pixel Grid'` and sets `--font-zen-pixel-grid`.
 *
 * Attach `.variable` to a wrapper to publish the custom property, or
 * `.className` to set the family directly on an element.
 *
 * @see {@link https://font.hanzo.ai Specimen and downloads}
 */
export declare const ZenPixelGrid: NextFontWithVariable;

/**
 * A display face drawn in line pixels. One weight — the five Pixel cuts are five drawings of one alphabet, not five weights of one drawing.
 *
 * Declares `font-family: 'Zen Pixel Line'` and sets `--font-zen-pixel-line`.
 *
 * Attach `.variable` to a wrapper to publish the custom property, or
 * `.className` to set the family directly on an element.
 *
 * @see {@link https://font.hanzo.ai Specimen and downloads}
 */
export declare const ZenPixelLine: NextFontWithVariable;

/**
 * A display face drawn in square pixels. One weight — the five Pixel cuts are five drawings of one alphabet, not five weights of one drawing.
 *
 * Declares `font-family: 'Zen Pixel Square'` and sets `--font-zen-pixel-square`.
 *
 * Attach `.variable` to a wrapper to publish the custom property, or
 * `.className` to set the family directly on an element.
 *
 * @see {@link https://font.hanzo.ai Specimen and downloads}
 */
export declare const ZenPixelSquare: NextFontWithVariable;

/**
 * A display face drawn in triangle pixels. One weight — the five Pixel cuts are five drawings of one alphabet, not five weights of one drawing.
 *
 * Declares `font-family: 'Zen Pixel Triangle'` and sets `--font-zen-pixel-triangle`.
 *
 * Attach `.variable` to a wrapper to publish the custom property, or
 * `.className` to set the family directly on an element.
 *
 * @see {@link https://font.hanzo.ai Specimen and downloads}
 */
export declare const ZenPixelTriangle: NextFontWithVariable;
